In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

Using the IMDB dataset of 250 most rated movies.

In [21]:
df = pd.read_csv('https://query.data.world/s/uikepcpffyo2nhig52xxeevdialfl7')

In [6]:
df.head()

Unnamed: 0                     Title  Year     Rated     Released  Runtime  \
0           1  The Shawshank Redemption  1994         R  14 Oct 1994  142 min   
1           2             The Godfather  1972         R  24 Mar 1972  175 min   
2           3    The Godfather: Part II  1974         R  20 Dec 1974  202 min   
3           4           The Dark Knight  2008     PG-13  18 Jul 2008  152 min   
4           5              12 Angry Men  1957  APPROVED  01 Apr 1957   96 min   

                  Genre              Director  \
0          Crime, Drama        Frank Darabont   
1          Crime, Drama  Francis Ford Coppola   
2          Crime, Drama  Francis Ford Coppola   
3  Action, Crime, Drama     Christopher Nolan   
4          Crime, Drama          Sidney Lumet   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola (screenplay), Mario Puzo ...   
3  Jonathan Nolan (screenplay), Christopher Nolan...   
4  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors   ...    tomatoConsensus  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   ...                NaN   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   ...                NaN   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   ...                NaN   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   ...                NaN   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   ...                NaN   

  tomatoUserMeter tomatoUserRating tomatoUserReviews  \
0             NaN              NaN               NaN   
1             NaN              NaN               NaN   
2             NaN              NaN               NaN   
3             NaN              NaN               NaN   
4             NaN              NaN               NaN   

                                           tomatoURL          DVD  \
0  http://www.rottentomatoes.com/m/shawshank_rede...  27 Jan 1998   
1         http://www.rottentomatoes.com/m/godfather/  09 Oct 2001   
2  http://www.rottentomatoes.com/m/godfather_part...  24 May 2005   
3   http://www.rottentomatoes.com/m/the_dark_knight/  09 Dec 2008   
4  http://www.rottentomatoes.com/m/1000013-12_ang...  06 Mar 2001   

      BoxOffice                       Production  \
0           NaN                Columbia Pictures   
1           NaN               Paramount Pictures   
2           NaN               Paramount Pictures   
3  $533,316,061  Warner Bros. Pictures/Legendary   
4           NaN             Criterion Collection   

                                             Website Response  
0                                                NaN     True  
1                        http://www.thegodfather.com     True  
2                       http://www.thegodfather.com/     True  
3               http://thedarkknight.warnerbros.com/     True  
4  http://www.criterion.com/films/27871-12-angry-men     True  

[5 rows x 38 columns]

In [4]:
df.columns

Index(['Unnamed: 0', 'Title', 'Year', 'Rated', 'Released', 'Runtime', 'Genre',
       'Director', 'Writer', 'Actors', 'Plot', 'Language', 'Country', 'Awards',
       'Poster', 'Ratings.Source', 'Ratings.Value', 'Metascore', 'imdbRating',
       'imdbVotes', 'imdbID', 'Type', 'tomatoMeter', 'tomatoImage',
       'tomatoRating', 'tomatoReviews', 'tomatoFresh', 'tomatoRotten',
       'tomatoConsensus', 'tomatoUserMeter', 'tomatoUserRating',
       'tomatoUserReviews', 'tomatoURL', 'DVD', 'BoxOffice', 'Production',
       'Website', 'Response'],
      dtype='object')

In [22]:
df = df[['Title', 'Year','Genre','Director','Actors','Plot', 'Language', 'Country', 'imdbRating']]
df.head()

Title  Year                 Genre              Director  \
0  The Shawshank Redemption  1994          Crime, Drama        Frank Darabont   
1             The Godfather  1972          Crime, Drama  Francis Ford Coppola   
2    The Godfather: Part II  1974          Crime, Drama  Francis Ford Coppola   
3           The Dark Knight  2008  Action, Crime, Drama     Christopher Nolan   
4              12 Angry Men  1957          Crime, Drama          Sidney Lumet   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot  \
0  Two imprisoned men bond over a number of years...   
1  The aging patriarch of an organized crime dyna...   
2  The early life and career of Vito Corleone in ...   
3  When the menace known as the Joker emerges fro...   
4  A jury holdout attempts to prevent a miscarria...   

                                     Language  Country  imdbRating  
0                                     English      USA         9.3  
1                     English, Italian, Latin      USA         9.2  
2  English, Italian, Spanish, Latin, Sicilian      USA         9.0  
3                           English, Mandarin  USA, UK         9.0  
4                                     English      USA         8.9

In [23]:
df = df[['Title', 'Year','Genre','Director','Actors','Plot']]

In [11]:
!pip install rake_nltk

  Created wheel for rake-nltk: filename=rake_nltk-1.0.4-py2.py3-none-any.whl size=7010 sha256=69d729118aa218686c0cc2a0d884260a7772e64e169c106e94366b1d3c8c2cbf
  Stored in directory: C:\Users\huzef\AppData\Local\pip\Cache\wheels\ef\92\fc\271b3709e71a96ffe934b27818946b795ac6b9b8ff8682483f
Successfully built rake-nltk


In [14]:
from rake_nltk import Rake

In [83]:
# TEST W/  &  W/O  YEAR ---- Taking the decades of the year ____________try this
# TEST  COMBINING PEOPLE+PLOT AND GENRE   &&&   KEEPING THEM APART



# 1. W/ YEAR  &   COMBINED
rake = Rake()
ans = []
for row in df.itertuples():
    rake.extract_keywords_from_text(row.Plot)
    genre = [''.join(d.lower().split(' ')) for d in row.Genre.split(',')]
    directors = [''.join(d.lower().split(' ')) for d in row.Director.split(',')]
    actors = [''.join(d.lower().split(' ')) for d in row.Actors.split(',')]
    ans.append(str(row.Year)[2] +' '+ ' '.join(list(rake.frequency_dist) + genre + directors + actors) )
df['tokens'] = pd.Series(ans)

In [88]:
df.tokens[100]

'5 stand union longshoreman prize ex corrupt fighter turned bosses struggles crime drama thriller eliakazan marlonbrando karlmalden leej.cobb rodsteiger'

In [93]:
count = CountVectorizer()
count_matrix = count.fit_transform(df['tokens'])

cos_similarity = cosine_similarity(count_matrix, count_matrix)

cos_similarity

array([[1.        , 0.14638501, 0.1315587 , ..., 0.05      , 0.05      ,
        0.05270463],
       [0.14638501, 1.        , 0.34236839, ..., 0.048795  , 0.048795  ,
        0.05143445],
       [0.1315587 , 0.34236839, 1.        , ..., 0.0438529 , 0.0438529 ,
        0.04622502],
       ...,
       [0.05      , 0.048795  , 0.0438529 , ..., 1.        , 0.05      ,
        0.05270463],
       [0.05      , 0.048795  , 0.0438529 , ..., 0.05      , 1.        ,
        0.05270463],
       [0.05270463, 0.05143445, 0.04622502, ..., 0.05270463, 0.05270463,
        1.        ]])

In [125]:
def get_10_similar_movies_for(movie, sim=cos_similarity):
    titles = df.Title
    for title in titles:
        if title == movie:
            break
    else:
        return 'Incorrect movie title or Movie not in data!'
    indices = sorted(enumerate(cos_similarity[titles[titles==movie].index[0]]), key=lambda x:x[1], reverse=True)[1:11]
    return [titles[i[0]] for i in indices]

In [104]:
for title in df.Title:
    if title == 'Batman Begins':
        print('Yes')

Yes


In [126]:
my_fav_movie = 'Batman Begins'

get_10_similar_movies_for(my_fav_movie)

['The Dark Knight',
 'The Dark Knight Rises',
 'Spider-Man: Homecoming',
 'Star Wars: Episode V - The Empire Strikes Back',
 'The Prestige',
 'Guardians of the Galaxy Vol. 2',
 'Baby Driver',
 'Sin City',
 'Inception',
 'Song of the Sea']

In [127]:
get_10_similar_movies_for('Tawshank Redemption')

'Incorrect movie title or Movie not in data!'

In [128]:
get_10_similar_movies_for('The Shawshank Redemption')

['Pulp Fiction',
 'Rope',
 'Se7en',
 'Goodfellas',
 'Butch Cassidy and the Sundance Kid',
 'The Godfather',
 'Papillon',
 'The Green Mile',
 'Casino',
 'The Godfather: Part II']

In [129]:
get_10_similar_movies_for('The Dark Knight')

['Batman Begins',
 'The Dark Knight Rises',
 'The Prestige',
 'The Green Mile',
 'Out of the Past',
 'Witness for the Prosecution',
 'Rush',
 'The Godfather',
 'Reservoir Dogs',
 'V for Vendetta']

In [130]:
# TEST W/  &  W/O  YEAR ---- Taking the decades of the year ____________try this
# TEST  COMBINING PEOPLE+PLOT AND GENRE   &&&   KEEPING THEM APART



# 2. W/O YEAR  &   COMBINED
rake = Rake()
ans = []
for row in df.itertuples():
    rake.extract_keywords_from_text(row.Plot)
    genre = [''.join(d.lower().split(' ')) for d in row.Genre.split(',')]
    directors = [''.join(d.lower().split(' ')) for d in row.Director.split(',')]
    actors = [''.join(d.lower().split(' ')) for d in row.Actors.split(',')]
    ans.append(' '.join(list(rake.frequency_dist) + genre + directors + actors) )
df['tokens'] = pd.Series(ans)

In [132]:
df['tokens'][100]

'stand union longshoreman prize ex corrupt fighter turned bosses struggles crime drama thriller eliakazan marlonbrando karlmalden leej.cobb rodsteiger'

In [131]:
count = CountVectorizer()
count_matrix = count.fit_transform(df['tokens'])

cos_similarity = cosine_similarity(count_matrix, count_matrix)

cos_similarity

array([[1.        , 0.14638501, 0.1315587 , ..., 0.05      , 0.05      ,
        0.05270463],
       [0.14638501, 1.        , 0.34236839, ..., 0.048795  , 0.048795  ,
        0.05143445],
       [0.1315587 , 0.34236839, 1.        , ..., 0.0438529 , 0.0438529 ,
        0.04622502],
       ...,
       [0.05      , 0.048795  , 0.0438529 , ..., 1.        , 0.05      ,
        0.05270463],
       [0.05      , 0.048795  , 0.0438529 , ..., 0.05      , 1.        ,
        0.05270463],
       [0.05270463, 0.05143445, 0.04622502, ..., 0.05270463, 0.05270463,
        1.        ]])

In [133]:
my_fav_movie = 'Batman Begins'

get_10_similar_movies_for(my_fav_movie)

['The Dark Knight',
 'The Dark Knight Rises',
 'Spider-Man: Homecoming',
 'Star Wars: Episode V - The Empire Strikes Back',
 'The Prestige',
 'Guardians of the Galaxy Vol. 2',
 'Baby Driver',
 'Sin City',
 'Inception',
 'Song of the Sea']

In [127]:
get_10_similar_movies_for('Tawshank Redemption')

'Incorrect movie title or Movie not in data!'

In [134]:
get_10_similar_movies_for('The Shawshank Redemption')

['Pulp Fiction',
 'Rope',
 'Se7en',
 'Goodfellas',
 'Butch Cassidy and the Sundance Kid',
 'The Godfather',
 'Papillon',
 'The Green Mile',
 'Casino',
 'The Godfather: Part II']

In [135]:
get_10_similar_movies_for('The Dark Knight')

['Batman Begins',
 'The Dark Knight Rises',
 'The Prestige',
 'The Green Mile',
 'Out of the Past',
 'Witness for the Prosecution',
 'Rush',
 'The Godfather',
 'Reservoir Dogs',
 'V for Vendetta']

## So the presence of the decade number isn't affecting the reccomendation, atleast not visibly

In [136]:
# 3. WORKING SOLELY ON GENRE+PLOT


rake = Rake()
ans = []
for row in df.itertuples():
    rake.extract_keywords_from_text(row.Plot)
    genre = [''.join(d.lower().split(' ')) for d in row.Genre.split(',')]
    ans.append(' '.join(list(rake.frequency_dist) + genre) )
df['tokens'] = pd.Series(ans)

In [137]:
count = CountVectorizer()
count_matrix = count.fit_transform(df['tokens'])

cos_similarity = cosine_similarity(count_matrix, count_matrix)

cos_similarity

array([[1.        , 0.2       , 0.16903085, ..., 0.06666667, 0.06900656,
        0.0745356 ],
       [0.2       , 1.        , 0.3380617 , ..., 0.06666667, 0.06900656,
        0.0745356 ],
       [0.16903085, 0.3380617 , 1.        , ..., 0.05634362, 0.05832118,
        0.06299408],
       ...,
       [0.06666667, 0.06666667, 0.05634362, ..., 1.        , 0.06900656,
        0.0745356 ],
       [0.06900656, 0.06900656, 0.05832118, ..., 0.06900656, 1.        ,
        0.07715167],
       [0.0745356 , 0.0745356 , 0.06299408, ..., 0.0745356 , 0.07715167,
        1.        ]])

In [142]:
my_fav_movie = 'Batman Begins'

get_10_similar_movies_for(my_fav_movie)

['Spider-Man: Homecoming',
 'The Dark Knight',
 'Star Wars: Episode V - The Empire Strikes Back',
 'Guardians of the Galaxy Vol. 2',
 'Sin City',
 'Baby Driver',
 'Song of the Sea',
 'The Wolf of Wall Street',
 'The Dark Knight Rises',
 'Out of the Past']

In [144]:
get_10_similar_movies_for('The Shawshank Redemption')

['Pulp Fiction',
 'Rope',
 'Butch Cassidy and the Sundance Kid',
 'Goodfellas',
 'The Godfather',
 'Se7en',
 'Papillon',
 'Cool Hand Luke',
 'Casino',
 'No Country for Old Men']

In [145]:
get_10_similar_movies_for('The Dark Knight')

['The Dark Knight Rises',
 'Batman Begins',
 'The Green Mile',
 'Witness for the Prosecution',
 'Rush',
 'Out of the Past',
 'The Godfather',
 'Reservoir Dogs',
 'V for Vendetta',
 'The Silence of the Lambs']

## so we can see that we are getting movies similar to the genre and plot
## while there is no metric right now (except our intuition and movie-knowledge), we cant say whether adding the actors and directors is a better option or not.